name: ci

on:
  pull_request:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: Set up Go and test and lint
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./...
      - run: go test -cover
      - run: go fmt
